site_name: TFM CDD Evaluación

theme:
  name: material

nav:
  - Inicio: index.md
  - Arquitectura: arquitectura.md
  - Desarrollo de pruebas: desarrollo-pruebas.md
  - Instalación y estado actual: instalacion.md
